<BatteryLayout>:
    orientation: "vertical"
    padding: 20
    spacing: 20

    Label:
        text: "🔋 Battery AI"
        font_size: "28sp"

    Label:
        id: level_label
        text: "Niveau : ..."

    Label:
        id: temp_label
        text: "Température : ..."

    Label:
        id: voltage_label
        text: "Voltage : ..."

    Label:
        id: conseil_label
        text: "Conseil"
